const common = { datePublished: '2026-09-23', dateModified: '2026-09-23', updated: 'Updated Sep 2026' };

export const evergreenGuides = {
  'co-manufacturer-selection': { ...common, title: 'How to Find, Vet, and Scale With the Right Co-Manufacturer', titleBefore: 'How to Find, Vet, and Scale With the Right', titleAccent: 'Co-Manufacturer', description: 'A practical co-manufacturer selection guide for scaling CPG brands: capacity, quality, economics, communication, and the questions to ask before you commit.', keywords: 'how to find a co-manufacturer, co-packer selection, CPG co-manufacturer, co-manufacturer vetting checklist', lede: 'The wrong co-manufacturer creates problems that look like demand problems, inventory problems, or cash problems. Usually, they start with a rushed selection process. This guide gives you a way to evaluate the operation before you hand it your next production run.', readTime: '14 min read', sections: [
    { id: 'right-fit', heading: 'The right co-man is more than available capacity', lead: 'A factory can have an open line and still be the wrong partner. You are choosing a system that has to protect quality, timing, cash, and your relationship with customers.', cards: [
      { title: 'Capacity that matches your growth', body: 'Ask what is available now, what is committed, and what happens when your volume doubles. “We can fit you in” is not a capacity plan.' },
      { title: 'Process discipline', body: 'Look for documented change control, batch records, QC release, deviation handling, and a clear owner for each handoff.' },
      { title: 'Commercial fit', body: 'Minimums, payment terms, setup fees, testing, tooling, and lead times determine whether the partnership works at your actual stage.' },
      { title: 'Communication under pressure', body: 'The best predictor is not the polished tour. It is how clearly the team answers uncomfortable questions about delays, defects, and constraints.' },
    ] },
    { id: 'vet', heading: 'A practical co-manufacturer vetting process', paragraphs: ['Treat selection like an operating project, not a vendor beauty contest. Give each candidate the same brief, the same questions, and the same request for evidence. That makes the comparison useful.', 'Request a sample production schedule, a representative quality document, an example of how they handle a deviation, and a complete quote that states assumptions. If a candidate will not show you how the work is controlled, assume you will be controlling it later.'], steps: [
      { title: 'Write the production brief', body: 'Define SKU, format, forecast, target volume, ingredients or materials, packaging, testing, certifications, launch date, and acceptable substitutions.' },
      { title: 'Screen for capability', body: 'Confirm equipment, batch sizes, line speeds, allergen or material controls, storage, certifications, and experience with your product category.' },
      { title: 'Validate the economics', body: 'Compare total cost, not just conversion cost. Include setup, testing, freight, packaging, scrap, minimums, payment terms, and the cost of waiting.' },
      { title: 'Run a reference check', body: 'Ask former or current customers what happens when a forecast changes, a batch fails, or a retailer moves a launch date.' },
    ] },
    { id: 'scale', heading: 'What to put in place before the first production run', paragraphs: ['Your operating system should exist before production starts. Freeze the approved formula or specification, define the quality release process, agree on the production calendar, and document who can approve changes.', 'Set a weekly operating review during scale-up. Review forecast versus order, production status, open quality issues, materials at risk, and decisions needed. The goal is not more meetings. It is fewer surprises.'], callout: { label: 'Operator rule.', body: 'If a change matters to cost, quality, timing, or customer experience, it belongs in writing before it reaches the line.' } },
  ], faq: [
    { q: 'What is the difference between a co-manufacturer and a co-packer?', a: 'The terms overlap. A co-packer typically manufactures and packs a product to your specification. A co-manufacturer may provide a broader production relationship, including sourcing, formulation, packaging, and process development. Define the actual scope in the agreement.' },
    { q: 'How many co-manufacturers should we evaluate?', a: 'Evaluate enough candidates to understand the market and create a real comparison, usually three to five qualified operators. More names are not helpful if they have not passed the capability screen.' },
    { q: 'When should a growing brand switch co-manufacturers?', a: 'Consider a change when repeated quality failures, missed commitments, poor visibility, or structurally bad economics are limiting growth—and when the current partner has no credible corrective plan.' },
  ], related: [{ href: '/guides/co-manufacturer-contracts-risk', title: 'Co-Manufacturer Contracts and Risk', description: 'What to protect before you sign.' }, { href: '/guides/cpg-demand-forecasting', title: 'Demand Forecasting for CPG Brands', description: 'The forecast your production plan is built on.' }] },

  'cpg-demand-forecasting': { ...common, title: 'Demand Forecasting for CPG Brands: From Spreadsheet Guessing to Operational Control', titleBefore: 'Demand Forecasting for CPG Brands:', titleAccent: 'From Guessing to Control', description: 'A practical demand planning guide for CPG brands managing inventory, retail growth, production lead times, and working capital.', keywords: 'CPG demand forecasting, inventory planning CPG, demand planning small brand, S&OP for emerging brands', lede: 'A forecast is not a prediction you hope is right. It is the operating assumption your purchasing, production, cash, and customer promises are built on. Make the assumption visible, update it often, and give every decision an owner.', readTime: '13 min read', sections: [
    { id: 'why', heading: 'Why forecasting breaks as brands scale', paragraphs: ['Early-stage brands can run on intuition because the founder is close to every order. That stops working when sales split across DTC, wholesale, marketplaces, distributors, and retail. Each channel has different timing, order behavior, and data quality.', 'The common failure is a single annual number treated as a plan. Operations needs a rolling view by SKU, channel, customer, and month—with a clear distinction between what has been ordered, what is expected, and what is merely hoped for.'] },
    { id: 'model', heading: 'Build a forecast people can operate', cards: [
      { title: 'Start with the demand signal', body: 'Separate shipped orders, retailer orders, subscriptions, promotions, pipeline, and one-time events. Do not blend committed demand with a sales wish list.' },
      { title: 'Forecast at SKU and channel level', body: 'A total-company forecast hides the stockout. Plan the items that actually drive service levels, margin, and production constraints.' },
      { title: 'Add the timing reality', body: 'Include production lead time, component lead time, ocean or domestic freight, receiving, QC, and retailer appointment windows.' },
      { title: 'Show a range', body: 'Use base, upside, and downside cases. The point is not false precision. It is making the cash and capacity implications of uncertainty visible.' },
    ] },
    { id: 'rhythm', heading: 'The monthly planning rhythm', paragraphs: ['A useful forecast is a recurring conversation between sales, finance, marketing, and operations. It does not need enterprise software. It needs a shared file, a calendar, and decisions that do not disappear in a meeting.', 'Review actuals versus forecast, update the next 90 days, flag supply constraints, and decide what changes. Keep a short record of the assumptions behind the forecast so next month’s variance teaches you something.'], table: { headers: ['Review', 'Question', 'Owner'], rows: [['Demand', 'What changed in orders, velocity, or pipeline?', 'Sales / marketing'], ['Supply', 'What can we make, buy, receive, and release?', 'Operations'], ['Cash', 'What does the plan require us to fund?', 'Finance / founder'], ['Decision', 'What changes today because of the new information?', 'Leadership']] } },
    { id: 'signals', heading: 'The signals that deserve attention', paragraphs: ['Forecast accuracy is not the only measure. Watch bias, stockout risk, excess inventory, supplier lead-time variance, and the number of manual overrides. A forecast that is consistently optimistic is more dangerous than one that is simply imperfect.', 'When a SKU misses plan, ask whether the problem was demand, availability, price, placement, or execution. That diagnosis determines whether you change the forecast or fix the system.'], callout: { label: 'Simple test.', body: 'If your forecast cannot tell you what you should buy, make, or delay this month, it is reporting—not planning.' } },
  ], faq: [
    { q: 'How far out should a CPG brand forecast?', a: 'Use a detailed 90-day operating forecast and a lighter six- to 18-month view for capacity, cash, and major commitments. The right horizon depends on lead times and retailer calendars.' },
    { q: 'Should we forecast by revenue or units?', a: 'Use units for production and inventory decisions, then translate to revenue and cash. Revenue alone can hide SKU mix and channel differences.' },
    { q: 'What if our historical data is too limited?', a: 'Start with explicit assumptions and a range. Use comparable products, launch timing, channel commitments, and weekly updates. A transparent imperfect forecast beats an opaque precise-looking one.' },
  ], related: [{ href: '/blog/retail-inventory-planning-90-day', title: 'Retail Inventory Planning in 90 Days', description: 'A closer look at the retail ramp.' }, { href: '/guides/cpg-gross-margin-playbook', title: 'The CPG Gross Margin Playbook', description: 'Connect volume decisions to margin.' }] },

  'cpg-gross-margin-playbook': { ...common, title: 'CPG Gross Margin Playbook: Where Margin Leaks and How to Fix It', titleBefore: 'CPG Gross Margin:', titleAccent: 'Where Margin Leaks', description: 'A practical gross margin and unit economics framework for consumer brands: product cost, freight, packaging, channel deductions, and inventory.', keywords: 'CPG gross margin, CPG unit economics, margin optimization consumer brand, gross margin analysis CPG', lede: 'Revenue can grow while the business gets weaker. Gross margin tells you whether each additional order creates room to operate—or creates more work at a loss. This guide shows where margin disappears and how to find it.', readTime: '13 min read', sections: [
    { id: 'waterfall', heading: 'Build the margin waterfall before chasing growth', paragraphs: ['Start with the net revenue you actually keep. Subtract discounts, promotions, distributor or retailer deductions, and chargebacks before you call the remainder margin. Then work down through product, packaging, freight, warehousing, and fulfillment.', 'The useful unit is not always the SKU. For a multi-channel brand, calculate margin by SKU and channel. A product can be healthy DTC and unattractive in wholesale once freight, commissions, and retailer requirements are included.'] },
    { id: 'leaks', heading: 'The five places margin usually leaks', cards: [
      { title: 'Product cost', body: 'Small formula, material, or MOQ changes compound quickly. Track cost by current quote and by landed unit—not by an old purchase order.' },
      { title: 'Packaging and freight', body: 'Dimensional weight, case configuration, breakage, and expedited shipments can erase a good product margin.' },
      { title: 'Channel deductions', body: 'Chargebacks, promotions, broker commissions, distributor fees, and payment terms need a place in the model before the launch.' },
      { title: 'Inventory decisions', body: 'Excess inventory turns cash into storage and markdown risk. Stockouts turn margin into missed demand and rushed freight.' },
      { title: 'Operational rework', body: 'Every relabel, partial shipment, failed inspection, and manual correction has a cost. If it happens repeatedly, it belongs in the margin conversation.' },
    ] },
    { id: 'actions', heading: 'Turn the analysis into decisions', steps: [
      { title: 'Set a floor', body: 'Define the minimum contribution margin each channel and SKU must produce after variable costs. Make exceptions visible.' },
      { title: 'Rank the leaks', body: 'Quantify the biggest losses first. Do not spend a month negotiating a small packaging saving while expedited freight is eating the quarter.' },
      { title: 'Model the tradeoffs', body: 'Test MOQ, price, case pack, freight mode, and promotion scenarios. Show the volume required to make each option work.' },
      { title: 'Assign owners and dates', body: 'A margin model without an action owner is a report. Put every improvement into the same operating rhythm as inventory and production.' },
    ] },
    { id: 'board', heading: 'What founders and investors should see', paragraphs: ['A useful margin dashboard explains movement. Show gross margin by channel, landed cost by SKU, top deductions, freight variance, inventory exposure, and the actions underway.', 'Avoid a single blended margin number that hides an unprofitable channel. Clarity is more valuable than a flattering average.'], callout: { label: 'Operator rule.', body: 'Never approve growth that you have not modeled at the unit level. More orders do not fix bad economics.' } },
  ], faq: [{ q: 'What is a healthy gross margin for a CPG brand?', a: 'There is no universal target. Margin depends on category, channel, price point, freight, retailer terms, and marketing model. Use a channel-specific floor and make every major assumption explicit.' }, { q: 'What is the difference between gross margin and contribution margin?', a: 'Gross margin usually subtracts the direct cost of goods. Contribution margin goes further and includes variable costs such as fulfillment, payment fees, commissions, and channel-specific costs.' }, { q: 'How often should we update unit economics?', a: 'Review monthly during periods of change and at least quarterly once the operation is stable. Update immediately when pricing, freight, supplier cost, packaging, or channel terms change.' }], related: [{ href: '/guides/packaging-cost-reduction', title: 'Packaging Cost Reduction', description: 'Find savings without downgrading the brand.' }, { href: '/guides/cpg-demand-forecasting', title: 'Demand Forecasting for CPG Brands', description: 'Plan the volume behind the margin.' }] },

  'cpg-broker-selection-playbook': { ...common, title: 'How to Select, Manage, and Fire a CPG Broker', titleBefore: 'How to Select, Manage, and', titleAccent: 'Fire a CPG Broker', description: 'An operator’s playbook for choosing, managing, and replacing a CPG sales broker without losing visibility or retailer momentum.', keywords: 'CPG broker selection, food broker management, broker accountability CPG, how to choose a broker CPG', lede: 'A broker can open doors. They can also create a layer of expensive ambiguity between your brand and the shelf. The relationship works when ownership, targets, data, and consequences are clear.', readTime: '12 min read', sections: [
    { id: 'fit', heading: 'Choose the broker for the work you actually need', paragraphs: ['Do not start with the biggest logo. Start with the retailers, categories, regions, and buyer relationships that matter to your next 12 months. A broker that is impressive in a deck but weak in your category is not a fit.', 'Ask how the team sells, reports, forecasts, and handles a slow account. You are not only buying introductions. You are buying a repeatable operating motion.'] },
    { id: 'scorecard', heading: 'The broker scorecard', cards: [
      { title: 'Retailer access', body: 'Which buyers and accounts do they actively manage in your category? Ask for specifics, not a network claim.' },
      { title: 'Category fluency', body: 'Can they explain your velocity, margin, case pack, promotion, and replenishment constraints without hand-waving?' },
      { title: 'Operating cadence', body: 'What will you receive weekly and monthly? A list of meetings is not the same as a pipeline you can inspect.' },
      { title: 'Economics', body: 'Model commission, retainers, launch fees, travel, samples, promotions, and the internal time required to manage the relationship.' },
    ] },
    { id: 'manage', heading: 'Manage the relationship like a channel', steps: [{ title: 'Set targets by account', body: 'Agree on priority accounts, buyer meetings, listings, velocity, and timing. Put the targets in a shared tracker.' }, { title: 'Review evidence', body: 'Ask what happened, what changed, and what happens next. Require retailer feedback and next actions, not activity theater.' }, { title: 'Connect sales to operations', body: 'The broker needs current inventory, pricing, lead times, case packs, and launch constraints. Bad information creates bad retailer promises.' }, { title: 'Decide with a window', body: 'Give the relationship a clear review point. Continue when the evidence supports it. Change course when it does not.' }] },
    { id: 'exit', heading: 'When it is time to change brokers', paragraphs: ['Repeated missed follow-through, vague reporting, retailer promises your operation cannot keep, and no measurable progress are signals. So is a broker who cannot tell you why velocity is weak.', 'Read the agreement before you act. Confirm notice, account ownership, commissions, and transition obligations. Then protect the retailer relationship with a clean handoff and one source of truth.'], callout: { label: 'Operator rule.', body: 'Do not fire a broker because you are frustrated. Fire the relationship when the agreed evidence says it is not working.' } },
  ], faq: [{ q: 'When should a CPG brand hire a broker?', a: 'When the brand has a clear product, a realistic channel plan, and enough operational readiness to support the accounts the broker may open. A broker cannot fix an unclear offer or unreliable supply.' }, { q: 'How do CPG brokers typically get paid?', a: 'Common structures include commissions, retainers, launch fees, or combinations. Model the complete cost against the channel margin and expected volume.' }, { q: 'How long should we give a new broker?', a: 'Set a review window based on the sales cycle and retailer calendar. Define leading indicators such as meetings, submissions, and buyer feedback before waiting for final revenue.' }], related: [{ href: '/guides/regional-to-national-retail-expansion', title: 'From Regional to National', description: 'Build the operating system behind expansion.' }, { href: '/guides/distributor-onboarding-playbook', title: 'Distributor Onboarding Playbook', description: 'Make the handoff executable.' }] },

  'co-manufacturer-contracts-risk': { ...common, title: 'Co-Manufacturer Contracts: What to Negotiate, What to Protect, and What Goes Wrong', titleBefore: 'Co-Manufacturer Contracts:', titleAccent: 'What to Protect', description: 'An operational checklist for CPG brands reviewing co-manufacturer and co-packer agreements: specifications, capacity, quality, inventory, IP, and exit terms.', keywords: 'co-manufacturer contract, co-packer agreement, CPG manufacturing risk, co-man liability, co-manufacturer terms', lede: 'The contract is not paperwork after the operational decision. It is the operating system for what happens when demand changes, quality fails, materials arrive late, or one side needs to exit.', readTime: '13 min read', sections: [
    { id: 'before', heading: 'Read the agreement through an operator’s eyes', paragraphs: ['Legal review matters. So does operational review. The team running the relationship should be able to answer: what exactly is being made, who owns each input, what does “on time” mean, and what happens when reality changes?', 'Use the contract to remove ambiguity before the first purchase order. The cheapest dispute is the one you prevented with a clear definition.'] },
    { id: 'terms', heading: 'The terms that deserve real attention', cards: [{ title: 'Specifications and change control', body: 'Define the approved formula, materials, tolerances, packaging, testing, and who can approve a change.' }, { title: 'Capacity and lead times', body: 'State planning assumptions, reservation rules, minimum notice, and what happens when production is delayed.' }, { title: 'Quality and release', body: 'Define inspection, testing, batch release, nonconformance, rework, rejection, and investigation responsibilities.' }, { title: 'Inventory and ownership', body: 'Clarify raw materials, packaging, work in process, finished goods, storage, obsolescence, and transfer rights.' }, { title: 'Intellectual property', body: 'Document ownership of formulas, tooling, artwork, molds, process improvements, data, and confidential information.' }, { title: 'Exit and continuity', body: 'Set notice, transition support, record delivery, final production, inventory disposition, and customer continuity expectations.' }] },
    { id: 'risk', heading: 'Build a risk register before you sign', paragraphs: ['List the failure modes that would hurt the business most: a missed launch, a failed batch, a lost mold, an ingredient shortage, a retailer-specific packaging change, or a dispute over inventory. Assign each a prevention, a detection method, and an owner.', 'This is not pessimism. It is how you keep a contract connected to the physical work.'], table: { headers: ['Risk', 'Prevent', 'Detect'], rows: [['Quality failure', 'Approved spec and release process', 'Inspection, testing, deviation log'], ['Capacity shortfall', 'Production calendar and notice terms', 'Weekly schedule review'], ['Obsolete inventory', 'Forecast and approval rules', 'Aging report by SKU'], ['Supplier interruption', 'Approved alternates and safety stock', 'Lead-time and availability review']] } },
    { id: 'redflags', heading: 'Red flags before the first run', paragraphs: ['Be cautious when the quote is vague, the capacity answer changes by person, quality records are treated as proprietary, or the proposed process depends on one person remembering what was agreed.', 'Have counsel review legal terms. Have an operator test whether the terms can actually run the business. You need both.'], callout: { label: 'Important.', body: 'This is an operational checklist, not legal advice. Use a qualified attorney for the agreement and the jurisdictions involved.' } },
  ], faq: [{ q: 'Should a lawyer review a co-manufacturer agreement?', a: 'Yes. A qualified attorney should review the agreement. An operations review is complementary: it checks whether the legal terms describe the work clearly enough to execute.' }, { q: 'Who should own tooling and packaging inventory?', a: 'The agreement should state ownership, storage, maintenance, access, transfer, and disposition. Do not assume ownership is obvious because your brand paid the invoice.' }, { q: 'What is the most overlooked co-manufacturer term?', a: 'Exit and continuity terms are often underdeveloped. Define how records, materials, tooling, work in process, and customer commitments move if the relationship ends.' }], related: [{ href: '/guides/co-manufacturer-selection', title: 'Find the Right Co-Manufacturer', description: 'Vet the partner before you negotiate.' }, { href: '/blog/quality-containment-supplier-transition', title: 'Quality Containment During a Supplier Transition', description: 'Protect the business when something goes wrong.' }] },

  'regional-to-national-retail-expansion': { ...common, title: 'From Regional to National: The CPG Retail Expansion Playbook', titleBefore: 'From Regional to National:', titleAccent: 'The Retail Expansion Playbook', description: 'The operational playbook for CPG brands expanding from regional distribution into national retail: inventory, production, logistics, compliance, and cash.', keywords: 'CPG national retail expansion, regional to national CPG, scaling retail distribution, national distribution strategy', lede: 'National retail is not regional retail multiplied. The number of handoffs changes. The data gets noisier. The cost of being wrong gets larger. This is the operating checklist for making the jump without losing control.', readTime: '14 min read', sections: [
    { id: 'changes', heading: 'What changes at national scale', paragraphs: ['You add more retailers, distributors, warehouses, regions, calendars, routing requirements, and versions of the truth. A founder can no longer hold the full operation in memory.', 'The question is not whether the brand can sell nationally. It is whether the system can replenish nationally without creating stockouts, excess inventory, margin leakage, or quality drift.'] },
    { id: 'systems', heading: 'The six systems to make ready', cards: [{ title: 'Demand and inventory', body: 'Forecast by channel and SKU, then connect the forecast to purchase orders, production, safety stock, and cash.' }, { title: 'Production capacity', body: 'Reserve capacity, document alternates, and know which inputs or lines can become the constraint.' }, { title: 'Retail compliance', body: 'Centralize item data, case packs, pallet configurations, routing guides, EDI, ASN, and labeling requirements.' }, { title: 'Distribution network', body: 'Map lanes, warehouses, distributors, appointments, transit time, and the cost of expedited recovery.' }, { title: 'Commercial accountability', body: 'Give brokers, distributors, and internal teams targets, data, and a cadence for action.' }, { title: 'Financial visibility', body: 'Model working capital, deductions, payment terms, landed cost, and contribution margin by channel.' }] },
    { id: 'sequence', heading: 'Sequence the expansion instead of announcing it', steps: [{ title: 'Prove the operating cell', body: 'Choose a region, retailer group, or category and test the full order-to-cash flow before adding complexity.' }, { title: 'Document what worked', body: 'Turn the successful process into item setup, inventory, fulfillment, and escalation playbooks.' }, { title: 'Stress the assumptions', body: 'Model upside volume, delayed receipts, higher returns, retailer deductions, and a production disruption.' }, { title: 'Add complexity deliberately', body: 'Expand only when the team can explain what changes, who owns it, and how performance will be measured.' }] },
    { id: 'metrics', heading: 'The early warning dashboard', paragraphs: ['Track fill rate, on-time in-full, forecast bias, weeks of supply, aged inventory, production schedule adherence, deductions, freight variance, and cash tied up in inventory.', 'A national rollout should have a weekly exception review. The goal is not perfect reporting. It is knowing where the next failure is likely to come from.'], callout: { label: 'Operator rule.', body: 'Do not let a retailer launch date outrun your replenishment, compliance, and cash plan.' } },
  ], faq: [{ q: 'When is a brand ready for national retail?', a: 'When the brand can reliably forecast, produce, release, replenish, and report across its current channels—and has modeled the working-capital and operational requirements of the next step.' }, { q: 'Should we use a distributor for national expansion?', a: 'It depends on channel economics, retailer access, service requirements, and your internal capability. Model the full margin and operating workload rather than treating distribution as automatically simpler.' }, { q: 'What is the biggest national expansion mistake?', a: 'Treating the retailer win as the finish line. The hard work starts when the brand must repeatedly deliver the right product, in the right configuration, at the right time.' }], related: [{ href: '/guides/distributor-onboarding-playbook', title: 'Distributor Onboarding', description: 'Make the handoff work.' }, { href: '/guides/retail-readiness', title: 'The Retail Readiness Bible', description: 'The broader readiness checklist.' }] },

  'distributor-onboarding-playbook': { ...common, title: 'The CPG Distributor Onboarding Playbook', titleBefore: 'The CPG Distributor', titleAccent: 'Onboarding Playbook', description: 'A practical guide to distributor onboarding for emerging CPG brands: category reviews, item setup, inventory, EDI, routing, and launch sequencing.', keywords: 'distributor onboarding CPG, KeHE UNFI onboarding, category review process, new item setup distributor, distributor requirements', lede: 'Getting accepted by a distributor is not the same as being ready to ship through one. Onboarding is a chain of data, timing, inventory, compliance, and communication decisions. Miss one and the launch drifts.', readTime: '12 min read', sections: [
    { id: 'map', heading: 'Map the handoffs before the first order', paragraphs: ['Write down every handoff from approved item to replenishment: buyer or category review, item setup, pricing, distributor master data, EDI, packaging, inventory, routing, warehouse receipt, and deductions.', 'Give each handoff one owner and one definition of done. “Submitted” is not done. “Accepted, active, and ready for the first order” is done.'] },
    { id: 'setup', heading: 'The onboarding checklist', cards: [{ title: 'Commercial setup', body: 'Confirm pricing, terms, promotions, commissions, ship points, item authorization, and the effective date.' }, { title: 'Item data', body: 'Prepare dimensions, weights, UPCs, case pack, pallet configuration, shelf life, ingredients, images, and other required attributes.' }, { title: 'Systems', body: 'Test EDI or order workflows, acknowledgements, ASNs, invoices, and exception handling before volume arrives.' }, { title: 'Inventory', body: 'Position launch stock, safety stock, packaging, and replenishment assumptions against the distributor’s receiving and order cadence.' }, { title: 'Routing and compliance', body: 'Translate the routing guide into a shipment checklist that the warehouse can execute every time.' }, { title: 'Launch communication', body: 'Agree on contacts, escalation, first-order timing, forecast updates, and how changes will be communicated.' }] },
    { id: 'calendar', heading: 'Work backward from the category calendar', paragraphs: ['Distributor and retailer calendars can turn a small delay into a missed window. Start with the desired in-market date and work backward through approval, item setup, production, packaging, freight, receiving, and replenishment.', 'Build a decision deadline for every dependency. If the packaging proof is late, what moves? If inventory is short, who decides which accounts ship?'] },
    { id: 'launch', heading: 'The first 30 days after launch', steps: [{ title: 'Watch the first orders', body: 'Check order accuracy, fill rate, routing compliance, receiving issues, and deductions immediately.' }, { title: 'Compare plan to reality', body: 'Update the forecast using actual order cadence, not the original launch assumption.' }, { title: 'Resolve exceptions fast', body: 'Log every issue, assign an owner, and close the loop with the distributor.' }, { title: 'Document the repeatable process', body: 'Capture the item, order, ship, and invoice workflow before onboarding the next account.' }] },
  ], faq: [{ q: 'What data does a distributor need for item setup?', a: 'Requirements vary, but commonly include UPCs, dimensions, weights, case and pallet configuration, pricing, shelf life, product attributes, images, and regulatory or category information.' }, { q: 'How early should onboarding begin?', a: 'Start as soon as the commercial path is real. Work backward from the category and launch calendar, then add time for approval, production, freight, receiving, and issue resolution.' }, { q: 'Why do distributor launches create deductions?', a: 'Common causes include incorrect item data, routing violations, late or incomplete shipments, pricing mismatches, and invoices that do not match the distributor’s requirements.' }], related: [{ href: '/blog/kehe-compliance-requirements', title: 'KeHE Compliance Requirements', description: 'A focused compliance reference.' }, { href: '/blog/routing-guide-compliance-retail', title: 'Routing Guide Compliance', description: 'Translate requirements into execution.' }] },

  'cpg-channel-economics': { ...common, title: 'Amazon vs. DTC vs. Retail: The Operational Economics for CPG Brands', titleBefore: 'Amazon vs. DTC vs. Retail:', titleAccent: 'The Operational Economics', description: 'A channel economics framework for CPG brands comparing DTC, Amazon, wholesale, and retail through margin, inventory, fulfillment, and operating complexity.', keywords: 'Amazon vs retail CPG, DTC vs wholesale economics, CPG channel strategy, channel economics consumer brands', lede: 'Channel strategy is an operations decision. The channel changes the cost to serve, the inventory you need, the data you get, the margin you keep, and the work your team must absorb.', readTime: '13 min read', sections: [
    { id: 'compare', heading: 'Compare the operating model, not just the revenue', paragraphs: ['DTC gives you customer data and control, but you fund acquisition, fulfillment, returns, and service. Amazon gives you reach and a different demand signal, but fees, inventory placement, and platform rules change the economics. Retail gives you scale and credibility, but introduces compliance, deductions, distributor layers, and longer cash cycles.', 'There is no universally best channel. There is a channel mix that fits your product, margin, supply chain, and current capability.'] },
    { id: 'matrix', heading: 'A simple channel decision matrix', table: { headers: ['Dimension', 'DTC', 'Amazon', 'Retail / wholesale'], rows: [['Demand signal', 'Customer orders and campaigns', 'Marketplace velocity', 'POs, forecasts, replenishment'], ['Main operational burden', 'Pick, pack, returns, service', 'Fees, placement, platform rules', 'Compliance, routing, deductions'], ['Cash question', 'Acquisition before conversion', 'Inventory and fees', 'Terms and inventory funding'], ['Best use', 'Learning and relationship', 'Reach and conversion', 'Scale and credibility']] } },
    { id: 'model', heading: 'Model the full cost to serve', cards: [{ title: 'Net revenue', body: 'Start after discounts, promotions, marketplace fees, commissions, distributor terms, and deductions.' }, { title: 'Variable fulfillment', body: 'Include pick and pack, shipping, returns, storage, prep, customer service, and channel-specific requirements.' }, { title: 'Inventory and cash', body: 'Model lead times, minimums, safety stock, payment terms, and the cost of carrying product between order and cash.' }, { title: 'Management load', body: 'Count the people, systems, and exceptions required to run the channel. Operational complexity is a cost even when it is not on a vendor invoice.' }] },
    { id: 'sequence', heading: 'Choose the next channel by readiness', paragraphs: ['Before adding a channel, ask whether the operation can support the service promise. Do you have the data, inventory, packaging, fulfillment, compliance, and cash required? If not, the next channel may be a distraction disguised as growth.', 'A good channel plan names the trigger for expansion and the stop condition. That keeps the business from adding complexity simply because an opportunity appeared.'], callout: { label: 'Operator rule.', body: 'A channel is attractive only after you understand what it costs to serve an order there.' } },
  ], faq: [{ q: 'Is DTC more profitable than retail?', a: 'Not automatically. DTC may have higher gross revenue per order but also higher acquisition, fulfillment, return, and service costs. Compare contribution margin and cash cycle by channel.' }, { q: 'How should a brand decide between Amazon and retail?', a: 'Compare the customer and retailer access, fees, inventory requirements, data, margin, and operational capabilities. The answer depends on the product and the role each channel plays in the portfolio.' }, { q: 'Should every CPG brand sell in every channel?', a: 'No. A focused channel mix is often easier to operate and more profitable than being everywhere with inconsistent service and unclear economics.' }], related: [{ href: '/guides/cpg-gross-margin-playbook', title: 'The CPG Gross Margin Playbook', description: 'Make channel economics measurable.' }, { href: '/guides/regional-to-national-retail-expansion', title: 'Regional to National Expansion', description: 'Scale the channel without losing control.' }] },

  'sustainable-packaging-cpg': { ...common, title: 'Sustainable Packaging for CPG Brands: What Works, What Costs More, and What Retailers Require', titleBefore: 'Sustainable Packaging for CPG:', titleAccent: 'What Actually Works', description: 'A practical guide to sustainable packaging decisions for CPG, beauty, and wellness brands: material tradeoffs, cost, performance, compliance, and retail requirements.', keywords: 'sustainable packaging CPG, eco-friendly packaging costs, sustainable packaging tradeoffs, recyclable packaging retailers', lede: 'Sustainable packaging is not a material choice made in isolation. It is a performance, sourcing, cost, claims, and end-of-life decision that has to survive the supply chain and the shelf.', readTime: '12 min read', sections: [
    { id: 'tradeoffs', heading: 'Start with the job the package must do', paragraphs: ['Define the protection, shelf life, shipping, display, opening, and disposal requirements before choosing a material. A package that looks sustainable but fails in transit is not a sustainable system.', 'Ask what you can prove. Claims need evidence, and retailer or market requirements can change. Keep the specification, supplier documentation, testing, and claim language connected.'] },
    { id: 'framework', heading: 'The sustainable packaging decision framework', cards: [{ title: 'Performance', body: 'Does the package protect the product through production, freight, storage, fulfillment, and use?' }, { title: 'Material', body: 'What is it made from, how much of it is used, and what alternatives are genuinely available at your volume?' }, { title: 'Economics', body: 'Model tooling, minimums, conversion, freight, damage, assembly, and disposal—not only unit price.' }, { title: 'Claims', body: 'Define the evidence behind recycled, recyclable, compostable, renewable, or reduced-material claims.' }, { title: 'Retail fit', body: 'Confirm case pack, palletization, shelf presentation, labeling, and retailer requirements before you lock the design.' }, { title: 'End of life', body: 'Consider what a customer can realistically do with the package in the markets where it is sold.' }] },
    { id: 'sourcing', heading: 'Make the supplier and design decisions together', paragraphs: ['A material decision is only real when a qualified supplier can produce it at the required quality, volume, and timing. Ask for samples, test the package in the actual use case, and understand the supplier’s minimums and lead times.', 'Bring sourcing into the design process early. The cheapest time to discover a material or tooling constraint is before the design is final.'] },
    { id: 'measure', heading: 'What to measure after launch', paragraphs: ['Track damage, returns, material usage, package weight, cost variance, production yield, customer feedback, and claim performance. Sustainable packaging is a system you improve—not a badge you print once.', 'Be specific about tradeoffs. A smaller material reduction that works reliably may be better than a dramatic material switch that creates waste elsewhere.'], callout: { label: 'Operator rule.', body: 'Do not promise what the package cannot prove, produce, or survive.' } },
  ], faq: [{ q: 'Is recyclable packaging always more sustainable?', a: 'Not necessarily. The answer depends on material, local recovery systems, contamination, production inputs, transport, reuse, and actual consumer behavior. Evaluate the full system.' }, { q: 'How can sustainable packaging reduce cost?', a: 'Material reduction, right-sized formats, lower damage, better case packs, and fewer components can reduce cost. Sustainable changes can also increase tooling or conversion cost, so model both.' }, { q: 'When should sourcing be involved in packaging design?', a: 'Early. Supplier capability, minimums, tooling, lead time, testing, and available materials can materially change the design and the business case.' }], related: [{ href: '/guides/retail-ready-packaging', title: 'Getting Packaging Retail-Ready', description: 'Connect design to retail execution.' }, { href: '/guides/packaging-sourcing', title: 'Packaging Sourcing', description: 'Vet suppliers and model landed cost.' }] },

  'cpg-operations-kpis': { ...common, title: 'The CPG Operations KPI Dashboard: What to Track at Each Growth Stage', titleBefore: 'The CPG Operations KPI Dashboard:', titleAccent: 'What to Track', description: 'A practical KPI framework for consumer brand operations: service, inventory, production, cash, margin, and supplier performance.', keywords: 'CPG operations KPIs, supply chain metrics CPG, operations reporting consumer brand, inventory KPI CPG', lede: 'A dashboard should help you decide what to do next. If it only gives the team more numbers to report, it is not an operating system. These are the metrics that show where growth is creating risk.', readTime: '12 min read', sections: [
    { id: 'stages', heading: 'The right KPI changes as the business changes', paragraphs: ['A founder managing a handful of SKUs needs a different dashboard than a brand managing multiple retailers, distributors, and production partners. Start with the metrics that protect the next decision—not every metric your software can export.', 'Use a small core set, then add detail when a recurring problem needs diagnosis.'] },
    { id: 'core', heading: 'The core operating dashboard', cards: [{ title: 'Service', body: 'Fill rate, on-time in-full, order accuracy, and retailer compliance show whether customers receive what you promised.' }, { title: 'Inventory', body: 'Weeks of supply, stockouts, aged inventory, inventory turns, and forecast bias show where cash and demand are misaligned.' }, { title: 'Production', body: 'Schedule adherence, yield, quality release, batch or lot status, and supplier lead-time variance show whether supply can keep up.' }, { title: 'Cash and margin', body: 'Contribution margin, landed cost variance, deductions, payable timing, and cash tied up in inventory show whether growth is funding itself.' }, { title: 'Supplier performance', body: 'On-time delivery, defect rate, response time, corrective action closure, and price changes show whether partners are dependable.' }, { title: 'Execution load', body: 'Open exceptions, overdue decisions, manual workarounds, and aging tasks show whether the organization is quietly becoming the constraint.' }] },
    { id: 'cadence', heading: 'A dashboard is only useful with a cadence', table: { headers: ['Cadence', 'Review', 'Decision'], rows: [['Weekly', 'Exceptions, stockouts, late orders, production risk', 'What needs intervention now?'], ['Monthly', 'Forecast, inventory, margin, supplier performance', 'What changes in the operating plan?'], ['Quarterly', 'Capacity, channel economics, systems, team design', 'What capability does the next stage require?']] } },
    { id: 'design', heading: 'Design the dashboard for decisions', steps: [{ title: 'Define the metric', body: 'Write the formula, data source, time period, and owner. Different definitions create fake disagreement.' }, { title: 'Set a threshold', body: 'Decide what is healthy, watch, and urgent. A metric without a threshold is a decoration.' }, { title: 'Add a reason code', body: 'When a metric moves, classify why. This turns variance into learning.' }, { title: 'Assign the action', body: 'Every red metric needs an owner, a next step, and a date. Close the loop at the next review.' }] },
    { id: 'signal', heading: 'The dashboard should tell a story', paragraphs: ['If fill rate is falling, connect it to inventory, production, lead time, and cash. If margin is falling, connect it to freight, packaging, deductions, and channel mix. The value is in the relationship between metrics.', 'Keep the executive view short. Link to detailed trackers for the people doing the work.'], callout: { label: 'Operator rule.', body: 'Track fewer metrics well. A dashboard should make the next decision easier, not make the business look more sophisticated.' } },
  ], faq: [{ q: 'How many KPIs should a CPG brand track?', a: 'Start with a focused executive set, often eight to 15 metrics, then maintain deeper operational views by function. The right number is the smallest set that exposes risk and supports decisions.' }, { q: 'What is the most important supply chain KPI?', a: 'There is no single answer. Service, inventory, margin, cash, and supply reliability trade off against each other. The useful dashboard shows the system rather than optimizing one number.' }, { q: 'How often should operations KPIs be reviewed?', a: 'Review exceptions weekly, plan-level metrics monthly, and system or capability metrics quarterly. Increase cadence temporarily during a launch, disruption, or major channel change.' }], related: [{ href: '/blog/retail-fill-rate-scorecard', title: 'Retail Fill Rate Scorecard', description: 'A focused service-level reference.' }, { href: '/blog/supply-chain-audit-what-it-finds', title: 'What a Supply Chain Audit Finds', description: 'Turn visibility into action.' }] },
};
